### ISSUE TITLE
NameError: uninitialized constant UnitedStates::Pathname

### ISSUE THREAD

**Issue by kWhittington** [kWhittington/united_states#34]
This error is thrown whenever attempting to use the `UnitedStates.names` method from an `irb` console:
```bash
kwhittin at Kyles-MacBook-Pro in ~/D/P/R/playground (master|✔)
» gem install united_states
Fetching: united_states-1.2.0.gem (100%)
Successfully installed united_states-1.2.0
Parsing documentation for united_states-1.2.0
Installing ri documentation for united_states-1.2.0
Done installing documentation for united_states after 0 seconds
1 gem installed
kwhittin at Kyles-MacBook-Pro in ~/D/P/R/playground (master|✔)
» irb
irb(main):001:0> require 'united_states'
=> true
irb(main):002:0> UnitedStates.names
NameError: uninitialized constant UnitedStates::Pathname
        from /Users/kwhittin/.rvm/gems/ruby-2.3.1/gems/united_states-1.2.0/lib/united_states.rb:89:in `array_from_yaml_file'
        from /Users/kwhittin/.rvm/gems/ruby-2.3.1/gems/united_states-1.2.0/lib/united_states.rb:36:in `all'
        from /Users/kwhittin/.rvm/gems/ruby-2.3.1/gems/united_states-1.2.0/lib/united_states.rb:133:in `names'
        from (irb):2
        from /Users/kwhittin/.rvm/rubies/ruby-2.3.1/bin/irb:11:in `<main>'
```

**Comment by kWhittington** [comment]
closed by #35
